import { describe, it, expect } from 'vitest';
import { TRANSLATIONS } from './translations';

/**
 * zh_cn is derived from zh_hk at module load by a hand-maintained character map
 * (TRAD_TO_SIMP). That map silently no-ops on any character it does not know, so a
 * Traditional character missing an entry does not fail anything — it just renders in the
 * wrong script for a mainland reader. It had drifted to covering 123 of the 196 zh_hk
 * characters that need converting, leaking common words ("國", "業", "問", "銀") through.
 *
 * This gate pins the leak set at empty. It is deliberately a blocklist of characters known
 * to differ between the scripts rather than a full converter: the app cannot take an OpenCC
 * dependency for a build-time-constant string table, and a blocklist fails loudly the moment
 * zh_hk gains one of these characters without a matching map entry.
 */

const CJK = /[一-鿿]/;

/**
 * Traditional characters whose Simplified form differs. Generated by running OpenCC's t2s
 * table over the full CJK repertoire and keeping the characters that change, then narrowed
 * to those plausible in this UI's vocabulary. Extend freely — a false entry here can only
 * cause a failing test, never a wrong string.
 */
const TRADITIONAL_ONLY = new Set(
    ('並佔來債償內別則協參問啟嚴國圍圖執壽實審帶擇擋擬攬於暫桿業槓樣檢檻沒沖淨潛潤熱狀産畫礎稱筆級細終給綠維緒編緩虧見視觸註試諮變負責贈軸針銀銷閉頂項須' +
        '體個們價傳備優儲億劃動務區單報場壓夠對導專將屬帳幣廳張彙後從復態應慮損據數斷時書會條標機權歷歸殘決況減準測滙滿漲災為營獲現產當發盡監盤確積穩節簡' +
        '籤紀約純組結統經績總織續義習與舉華號衝複規覽觀計訊記設許評詢詳認誌說調請議識證財貨質資賬購費貸賣賺趨軟較載運過達選還這進連適遷遠遲鄰釋鑑開關閱間' +
        '險隨際電頁預類題額顧顯風騰驗鏈長門陳離雲靈點齊僅倉構櫃歐殼濟瀏盧碼禦繫聯職藝處術衛語讓買辦鍵鑰閃陰隱雜響頻麗齡傑極樓檔歲獎瑣環異範網線練緊縮繳' +
        '聲腦臺興舊蘋蘭蟲補裝親託訂診詞話該誤課論譯讀豐跡輛輸轉辭錄錢錯鋼鎖鏡階隊韓頭顏餘馬駕魯鳥麼黃齒簽戶匯僱遺囑殲歡殺滬無燈獸獵築紅紐紛繪').split(''),
);

const stringsOf = (node: unknown, out: string[] = []): string[] => {
    if (typeof node === 'string') out.push(node);
    else if (node && typeof node === 'object') for (const value of Object.values(node)) stringsOf(value, out);
    return out;
};

describe('i18n', () => {
    it('derives zh_cn with no Traditional characters left behind', () => {
        const leaked = new Set<string>();
        for (const text of stringsOf((TRANSLATIONS as Record<string, unknown>).zh_cn)) {
            for (const char of text) if (TRADITIONAL_ONLY.has(char)) leaked.add(char);
        }

        expect([...leaked].sort().join('')).toBe('');
    });

    it('keeps zh_cn structurally identical to zh_hk', () => {
        const cn = stringsOf((TRANSLATIONS as Record<string, unknown>).zh_cn);
        const hk = stringsOf((TRANSLATIONS as Record<string, unknown>).zh_hk);

        expect(cn).toHaveLength(hk.length);
        // Conversion is per-character, so lengths must match string for string. A map entry
        // that expanded or dropped a character would corrupt interpolation placeholders.
        expect(cn.map(s => s.length)).toEqual(hk.map(s => s.length));
    });

    it('leaves 覆 alone — it is unchanged in Simplified (覆蓋 -> 覆盖, never 复盖)', () => {
        // Guards the removed ['覆','复'] entry from being reinstated. It was dead only
        // because no zh_hk string contains 覆 today; the next one would have been corrupted.
        const hk = stringsOf((TRANSLATIONS as Record<string, unknown>).zh_hk);
        const cn = stringsOf((TRANSLATIONS as Record<string, unknown>).zh_cn);

        for (let i = 0; i < hk.length; i++) {
            for (let c = 0; c < hk[i].length; c++) {
                if (hk[i][c] === '覆') expect(cn[i][c]).toBe('覆');
            }
        }
    });

    it('has every CJK character in zh_cn either identical in zh_hk or a deliberate conversion', () => {
        // Sanity check on the walker itself: if this ever sees zero CJK it is silently
        // passing the tests above by reading nothing.
        const cjkCount = stringsOf((TRANSLATIONS as Record<string, unknown>).zh_cn)
            .flatMap(s => [...s]).filter(c => CJK.test(c)).length;

        expect(cjkCount).toBeGreaterThan(500);
    });
});
